version: "3"

services:
  php:
    build: ./php
    depends_on:
      - db
    volumes:
      - ../project:/var/www/html:cached

  web:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ../project:/var/www/html:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
  mongodb:
    image: mongo:3.6
    ports:
      - "27017:27017"
    command: --smallfiles
    #left use your host volume location
    #right use the default image setting ->/data/db/
    volumes:
      - ./mongodb/db:/data/db/
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
volumes:
  redis-data:
    driver: local